
version: 0.0
files:
  - source: TMP1
    destination: /tmp
  - source: TMP2
    destination: /tmp
  - source: TESTDIR1
    destination: /tmp


hooks:
  ApplicationStop:
    - location: scripts/app_stop
      timeout: 300
      runas: root
    - location: scripts/app_stop
      timeout: 300
      runas: root
# During the BeforeInstall deployment lifecycle event, run the commands
#   in the script specified in "location".
  BeforeInstall:
    - location: scripts/before_install
      timeout: 10
      runas: root
# During the AfterInstall deployment lifecycle event, run the commands
#   in the script specified in "location".
  AfterInstall:
    - location: scripts/after_install
      timeout: 20
      runas: root
# During the ApplicationInstall deployment lifecycle event, run the commands
#   in the script specified in "location".
  ApplicationStart:
    - location: scripts/app_start
      timeout: 15
      runas: root
# During the ValidateService deployment lifecycle event, run the commands
#   in the script specified in "location".
  ValidateService:
    - location: scripts/validate_service
      timeout: 20
      runas: root
